### PR TITLE
Update chinese-simplified.php

### PR DESCRIPTION
**Pull request by lzh370**

### CODE REVIEW

**Comment by mattpass** [comment]
Thanks for the translations @lzh370 - which of the 2 PRs should I look at, or do we need both?

**Comment by mattpass** [comment]
Ah my bad @lzh370, I realise now you've provided updates for both branches - thank you very much!

**Comment by lzh370** [comment]
You're welcome @mattpass . What's the difference between the dynamicpaths branch and the master branch?

**Comment by mattpass** [comment]
> You're welcome @mattpass . What's the difference between the dynamicpaths branch and the master branch?

It was started as a branch intended just to deal with getting ICEcoder working in: an iFrame, a top level wwwroot or any number of /sub/sub/sub/dirs ...as a lot of changes were needed. Was supposed to be the final item to do before 7.1 was released.

But then I kept covering extra items and it's ended up being a branch with a huge number of improvements and so ultimately it'll end up being v8.0. 😄 

Will be merging it into master very soon, hopefully next week!

**Comment by lzh370** [comment]
Good Job! @mattpass I'm looking forward to 8.0!

**Pull request merged**
